### ISSUE TITLE
Comments in stylesheet are parsed as well and break output

### ISSUE THREAD

**Issue by sn3p** [danschultzer/premailex#5]
I'm getting faulty output when inlining styles that include comments. Maybe strip the comments prior to inlining? A workaround for now is to get rid of the comments manually by running [cssnano](http://cssnano.co).

### Example 1

```css
h1 {
  font-weight: 700;
  /* color: red; */
}
```

```html
<h1 style=":*/;/* color:red;font-weight:700;">Hello world</h1>
```

### Example 2

```css
h1 {
  /* color: red; */
  font-weight: 700;
}

/* h1 {
  color: green;
} */
```

```html
<h1 style="*/
  font-weight:700;/* color:red;color:green;">Hello world</h1>
```
